"""followers

Revision ID: 38987f2c2932
Revises: 8bd5fd537d97
Create Date: 2020-04-05 21:45:17.405782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38987f2c2932'
down_revision = '8bd5fd537d97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
